#!/usr/bin/env python3
"""Write vessel model evaluation artifact scaffold."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def main() -> int:
    parser = argparse.ArgumentParser(description="Create an evaluation artifact skeleton for a candidate vessel model.")
    parser.add_argument("--model-id", required=True, help="Candidate model identifier.")
    parser.add_argument("--onnx-path", required=True, help="Path to candidate ONNX model.")
    parser.add_argument("--dataset-id", required=True, help="Evaluation dataset identifier.")
    parser.add_argument("--output-path", required=True, help="Output JSON path for evaluation metrics.")
    parser.add_argument("--map50", type=float, default=0.0, help="Optional manual metric input for scaffold runs.")
    parser.add_argument("--map50-95", dest="map50_95", type=float, default=0.0, help="Optional manual metric input.")
    parser.add_argument("--length-mae-m", dest="length_mae_m", type=float, default=0.0, help="Optional manual metric input.")
    parser.add_argument("--width-mae-m", dest="width_mae_m", type=float, default=0.0, help="Optional manual metric input.")
    parser.add_argument("--sanity-pass-rate", dest="sanity_pass_rate", type=float, default=0.0, help="Optional manual metric input.")
    args = parser.parse_args()

    output_path = Path(str(args.output_path)).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "schema_version": 1,
        "model_id": str(args.model_id).strip(),
        "onnx_path": str(Path(args.onnx_path).expanduser().resolve()),
        "dataset_id": str(args.dataset_id).strip(),
        "created_utc": _utc_now(),
        "metrics": {
            "map50": float(args.map50),
            "map50_95": float(args.map50_95),
            "length_mae_m": float(args.length_mae_m),
            "width_mae_m": float(args.width_mae_m),
            "sanity_pass_rate": float(args.sanity_pass_rate),
        },
        "status": "scaffold",
        "notes": "Metrics may be placeholder values unless generated by full evaluation pipeline.",
    }
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Evaluation artifact written: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
